//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/M144.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::M144_D0, // D0
	Gpio::M144_D1, // D1
	Gpio::M144_D2, // D2
	Gpio::M144_D4, // D4
	Gpio::M144_D5, // D5
	Gpio::M144_D6, // D6
	Gpio::M144_D7, // D7
	Gpio::M144_D8, // D8
	Gpio::M144_D9, // D9
	Gpio::M144_D10, // D10
	Gpio::M144_D11, // D11
	Gpio::M144_D12, // D12
	Gpio::M144_D13, // D13
	Gpio::M144_D14, // D14
	Gpio::M144_D15, // D15
	Gpio::M144_D16, // D16
	Gpio::M144_D17, // D17
	Gpio::M144_D18, // D18
	Gpio::M144_D19, // D19
	Gpio::M144_D20, // D20
	Gpio::M144_D21, // D21
	Gpio::M144_D22, // D22
	Gpio::M144_D23, // D23
	Gpio::M144_D24, // D24
	Gpio::M144_D25, // D25
	Gpio::M144_D26, // D26
	Gpio::M144_D27, // D27
	Gpio::M144_D28, // D28
	Gpio::M144_D29, // D29
	Gpio::M144_D30, // D30
	Gpio::M144_D31, // D31
	Gpio::M144_D32, // D32
	Gpio::M144_D33, // D33
	Gpio::M144_D34, // D34
	Gpio::M144_D35, // D35
	Gpio::M144_D36, // D36
	Gpio::M144_D37, // D37
	Gpio::M144_D38, // D38
	Gpio::M144_D39, // D39
	Gpio::M144_D40, // D40
	Gpio::M144_D41, // D41
	Gpio::M144_D42, // D42
	Gpio::M144_D43, // D43
	Gpio::M144_D44, // D44
	Gpio::M144_D45, // D45
	Gpio::M144_D46, // D46
	Gpio::M144_D47, // D47
	Gpio::M144_D48, // D48
	Gpio::M144_D49, // D49
	Gpio::M144_D50, // D50
	Gpio::M144_D51, // D51
	Gpio::M144_D52, // D52
	Gpio::M144_D53, // D53
// "D0",
// "D1",
// "D2",
// "D4",
// "D5",
// "D6",
// "D7",
// "D8",
// "D9",
// "D10",
// "D11",
// "D12",
// "D13",
// "D14",
// "D15",
// "D16",
// "D17",
// "D18",
// "D19",
// "D20",
// "D21",
// "D22",
// "D23",
// "D24",
// "D25",
// "D26",
// "D27",
// "D28",
// "D29",
// "D30",
// "D31",
// "D32",
// "D33",
// "D34",
// "D35",
// "D36",
// "D37",
// "D38",
// "D39",
// "D40",
// "D41",
// "D42",
// "D43",
// "D44",
// "D45",
// "D46",
// "D47",
// "D48",
// "D49",
// "D50",
// "D51",
// "D52",
// "D53",
}
