//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/M144.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A10: return "D0";
		case Gpio::A15: return "D13";
		case Gpio::A8: return "D12";
		case Gpio::A9: return "D1";
		case Gpio::B10: return "D14";
		case Gpio::B11: return "D15";
		case Gpio::B12: return "D34";
		case Gpio::B13: return "D31";
		case Gpio::B15: return "D2";
		case Gpio::B2: return "D28";
		case Gpio::B3: return "D40";
		case Gpio::B4: return "D39";
		case Gpio::B5: return "D41";
		case Gpio::B6: return "D43";
		case Gpio::B7: return "D42";
		case Gpio::B8: return "D45";
		case Gpio::B9: return "D44";
		case Gpio::C13: return "D53";
		case Gpio::C6: return "D8";
		case Gpio::C7: return "D9";
		case Gpio::C8: return "D10";
		case Gpio::C9: return "D11";
		case Gpio::D10: return "D6";
		case Gpio::D11: return "D7";
		case Gpio::D12: return "D32";
		case Gpio::D13: return "D33";
		case Gpio::D14: return "D30";
		case Gpio::D15: return "D29";
		case Gpio::D3: return "D19";
		case Gpio::D4: return "D18";
		case Gpio::D5: return "D16";
		case Gpio::D6: return "D17";
		case Gpio::D7: return "D35";
		case Gpio::D8: return "D4";
		case Gpio::D9: return "D5";
		case Gpio::E0: return "D46";
		case Gpio::E1: return "D47";
		case Gpio::E10: return "D23";
		case Gpio::E11: return "D22";
		case Gpio::E12: return "D21";
		case Gpio::E13: return "D20";
		case Gpio::E14: return "D37";
		case Gpio::E15: return "D24";
		case Gpio::E2: return "D48";
		case Gpio::E3: return "D49";
		case Gpio::E4: return "D50";
		case Gpio::E5: return "D51";
		case Gpio::E6: return "D52";
		case Gpio::E7: return "D27";
		case Gpio::E8: return "D26";
		case Gpio::E9: return "D25";
		case Gpio::G14: return "D36";
		case Gpio::G15: return "D38";
		default: return nullptr;
	}
	return nullptr;
}
